# Generated by Django 4.2.30 on 2026-09-03 12:07

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filieres', '0001_initial'),
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('annee_academique', models.CharField(max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('nombre_pages', models.PositiveIntegerField(default=0)),
                ('type_contenu', models.CharField(choices=[('EXAM', 'Examen'), ('TD', 'Travaux dirigés'), ('CORRECTION', 'Corrigé'), ('COURSE', 'Support de cours')], default='EXAM', max_length=15)),
                ('fichier_original', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\error404\\Desktop\\examsecure\\backend\\media_private'), upload_to='originals/')),
                ('fichier_securise', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\error404\\Desktop\\examsecure\\backend\\media_private'), upload_to='secured/')),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=15)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='filieres.filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='matieres.matiere')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
