# Generated by Django 4.2.30 on 2026-09-09 15:51

import django.core.files.storage
from django.db import migrations, models


def copy_matiere_to_matieres(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM exams_epreuve LIKE 'matiere_id'")
        if cursor.fetchone():
            cursor.execute("SELECT id, matiere_id FROM exams_epreuve WHERE matiere_id IS NOT NULL")
            rows = cursor.fetchall()
            for doc_id, matiere_id in rows:
                cursor.execute(
                    "INSERT IGNORE INTO exams_epreuve_matieres (document_id, matiere_id) VALUES (%s, %s)",
                    [doc_id, matiere_id]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0001_initial'),
        ('exams', '0002_document_add_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='documents', to='matieres.matiere'),
        ),
        migrations.RunPython(copy_matiere_to_matieres, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='document',
            name='matiere',
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier_original',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\examsecure\\backend\\media_private'), upload_to='originals/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier_securise',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\examsecure\\backend\\media_private'), upload_to='secured/'),
        ),
    ]
