# Generated by Django 4.2.30 on 2026-09-03 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('moyen_paiement', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Carte bancaire')], default='MOBILE_MONEY', max_length=20)),
                ('reference_kkiapay', models.CharField(max_length=150, unique=True)),
                ('identifiant_externe', models.CharField(blank=True, max_length=150)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussie'), ('FAILED', 'Échouée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='exams.epreuve')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
