# Generated by Django 4.2.30 on 2026-09-08 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commentaire_etudiant',
            field=models.TextField(blank=True, help_text="Commentaire facultatif de l'étudiant"),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='motif_refus',
            field=models.TextField(blank=True, help_text="Motif obligatoire en cas de rejet par l'administrateur"),
        ),
        migrations.AddField(
            model_name='transaction',
            name='numero_telephone',
            field=models.CharField(blank=True, help_text="Numéro utilisé par l'étudiant pour effectuer le transfert", max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recu_fichier',
            field=models.FileField(blank=True, help_text='Preuve de paiement (Image ou PDF)', null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_recu',
            field=models.CharField(blank=True, help_text='Référence de transaction / SMS de confirmation', max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_kkiapay',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('UNPAID', 'Non payé'), ('PAYMENT_SUBMITTED', 'Paiement soumis'), ('PENDING_VERIFICATION', 'En attente de vérification'), ('PAID', 'Validé / Payé'), ('REJECTED', 'Refusé'), ('PENDING', 'En attente'), ('SUCCESS', 'Réussie'), ('FAILED', 'Échouée'), ('CANCELLED', 'Annulée')], default='PENDING_VERIFICATION', max_length=25),
        ),
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momo_number', models.CharField(default='+229 97 00 00 00', help_text='Numéro Mobile Money de réception des paiements (ex: +229 97 00 00 00)', max_length=50)),
                ('beneficiary_name', models.CharField(default='Administration ExamSecure', help_text='Nom du compte / bénéficiaire Mobile Money', max_length=150)),
                ('instructions', models.TextField(default="Pour accéder à cette épreuve, veuillez envoyer le montant indiqué au numéro Mobile Money de l'administration. Après le paiement, revenez dans l'application et envoyez votre reçu (capture d'écran ou PDF) pour vérification.", help_text="Consignes affichées à l'étudiant avant le paiement")),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Paiement Mobile Money',
                'verbose_name_plural': 'Configuration Paiement Mobile Money',
            },
        ),
    ]
