# Generated by Django 4.2.30 on 2026-09-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_epreuve_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentconfig',
            options={'verbose_name': 'Configuration Paiement Mobile Money', 'verbose_name_plural': 'Configurations Paiement Mobile Money'},
        ),
        migrations.RemoveField(
            model_name='paymentconfig',
            name='momo_number',
        ),
        migrations.RemoveField(
            model_name='paymentconfig',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='numero_celtis',
            field=models.CharField(blank=True, default='', help_text='Numéro Celtis de réception des paiements', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='numero_moov',
            field=models.CharField(blank=True, default='', help_text='Numéro Moov de réception des paiements', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='numero_mtn',
            field=models.CharField(blank=True, default='', help_text='Numéro MTN de réception des paiements', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='instructions',
            field=models.TextField(default="Pour accéder à ce document, veuillez envoyer le montant indiqué au(x) numéro(s) Mobile Money de l'administration. Après le paiement, revenez dans l'application et envoyez votre reçu (capture d'écran ou PDF) pour vérification.", help_text="Consignes affichées à l'étudiant avant le paiement"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='moyen_paiement',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money (Manuel)'), ('KKIAPAY', 'KkiaPay (Automatique)'), ('CARD', 'Carte bancaire')], default='MOBILE_MONEY', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Reçu soumis (En attente de validation)'), ('PAID', "Validé par l'administrateur"), ('REJECTED', "Rejeté par l'administrateur"), ('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échoué'), ('PAYMENT_SUBMITTED', 'Paiement soumis')], default='PENDING_VERIFICATION', max_length=25),
        ),
    ]
